### ISSUE TITLE
Player stops before playing last song

### ISSUE THREAD

**Issue by cweber** [dasevilla/rdiodj#16]
The player stops playing with one song left in the queue. It will not begin playing again once another song has been added. It requires a page refresh to start playing again.

**Comment by timball** [comment]
to add to this issue when rdiodj stops playing it stops for all users connect to room .

**Comment by rstecker** [comment]
I believe this issue has been fixed in the latest code (deployed on http://rdioparty.com/).  Please reopen if that's not the case.
