### ISSUE TITLE
rdio app + rdiodj interaction causes rdiodj to stop playing

### ISSUE THREAD

**Issue by timball** [dasevilla/rdiodj#18]
so team sunlight has been using rdiodj for a little bit today . this thing is great . 

issue : 
if i have rdio app up and use it to search for song or album and add a song to my "play later" queue this causes rdiodj to stop playing everywhere . 

--timball

**Comment by dasevilla** [comment]
This is a known bug with the Rdio JS API. The issue is how the queue is shared between different instances of Rdio.

**Comment by dasevilla** [comment]
There's a button now to continue playing if it's interrupted
