### ISSUE TITLE
Stable master player selection

### ISSUE THREAD

**Issue by dasevilla** [dasevilla/rdiodj#5]
Right now master player selection is flaky. If people are joining and leaving quickly, newly joined users will steal master. In some cases more than one user thinks they're master.

I think we could implement something similar to [ZooKeeper's leader election](http://zookeeper.apache.org/doc/trunk/recipes.html#sc_leaderElection).

**Comment by rstecker** [comment]
This has been resolved with http://rdioparty.com/ (though am not certain if it works for the heroku deploy... does it need to?)
