### ISSUE TITLE
Up-sell users to Rdio Unlimited accounts

### ISSUE THREAD

**Issue by superemily** [dasevilla/rdiodj#75]
Warn users and ask them to upgrade to Rdio Unlimited if they aren't able to play full tracks.

http://www.rdio.com/developers/docs/faq/ref-what-will-my-users-hear

**Comment by dasevilla** [comment]
Someone without an Rdio Unlimited subscription should get 30-second samples. If it's a track they can't hear, the player will just skip it.

**Comment by superemily** [comment]
30 second samples doesn't sound very fun. What do you guys think of requiring a full rdio account to use it? And same-region only rooms at least at first?

**Comment by dasevilla** [comment]
Requiring unlimited accounts sounds good. I don't think requiring same-region is a good idea, many tracks are available in multiple regions. Perhaps just a warning that the track isn't available in your region.

**Comment by jackdbernier** [comment]
We should drive sales and incite people to start a trial from within the app and then redirecting them to form to upgrade their accounts.

**Comment by jackdbernier** [comment]
Better region handling and incompatible tiers seem to be 2 different issues.

**Comment by dasevilla** [comment]
See #84 for handling different regions. This task will be for up-sells

**Comment by rstecker** [comment]
Now folks who have false for `canStreamHere` git a big popup telling them to subscribe and warning them about their impending 30s sample fate.
