### ISSUE TITLE
Improve design

### ISSUE THREAD

**Issue by dasevilla** [dasevilla/rdiodj#9]
http://cl.ly/image/14460y2n2k0w
http://cl.ly/image/2q1h2h2u3o36

**Comment by rstecker** [comment]
Updated mock from Jesse S:
![rdioparty_hackday_interfacecomp_v3](https://cloud.githubusercontent.com/assets/3209024/5911015/9b6cb9c4-a575-11e4-8492-4aa35545f88a.jpg)
