### ISSUE TITLE
Keeps playing same song on repeat

### ISSUE THREAD

**Issue by cweber** [dasevilla/rdiodj#91]
In the room I created, it keeps playing the same song over and over. There are other songs in the queue, but it never cycles into them. Sometimes it stops playing at all, so I refresh the page. All song remain in the queue and then it starts playing that same song again.

http://rdioparty.herokuapp.com/p/sunlight/

**Comment by jackdbernier** [comment]
The url you are using is outdated. If you try http://rdioparty.com, do you noticed the same behaviour ?
